spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mohaemukzip
    username: YOUR_USERNAME
    password: YOUR_PASSWORD

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: YOUR_JWT_SECRET

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,info,gatling  # 개발시 필요
  endpoint:
    prometheus:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY

gemini:
  recipe:
    api-key: YOUR_GEMINI_API_KEY  #레시피 챗봇
  summary:
    api-key: YOUR_GEMINI_RECIPE_KEY  #요약 생성용

youtube:
  api:
    key: YOUR_YOUTUBE_API_KEY