spring:
  application:
    name: mohaemukzip_BE

  jpa:
    database: mysql
    properties:
        hibernate:
            format_sql: true # SQL? ?? ?? ???

  profiles:
    active: dev
    include: openai # openai 프로파일 포함

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
        bucket: mohaemukzip-s3