global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mohaemukzip-api'
    static_configs:
      - targets: ['mohaemukzip-api:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter-mohaemukzip-prod:9100' ]

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter-mohaemukzip-prod:9121']